# config/main_config.yaml
project_name: "Time Series Forecasting Pipeline"

# Mapeamento de Pastas (Rastreabilidade MLOps)
results_paths:
  forecasts: "results/forecasts/"
  metrics: "results/metrics/"
  plots: "results/plots/"
  reports: "results/reports/"
  residuals: "results/residuals/"
  deep_learning: "results/forecasts/deep/"
  hybrid: "results/forecasts/hybrid/"
  hybrid_prophet: "results/forecasts/hybrid_prophet/"
  prophet: "results/forecasts/prophet/"
  arima: "results/forecasts/arima/"
  ets: "results/forecasts/ets/"
  statistical: "results/statistical/"

# Configurações Globais
random_seed: 42